name = "qcheck"
version = "1.0.3"

internal_modules = ["qcheck/test_error_message", "qcheck/internal/*"]

description = "QuickCheck-inspired property testing with integrated shrinking"
licences = ["Apache-2.0", "MIT"]
repository = { type = "github", user = "mooreryan", repo = "gleam_qcheck" }

[dependencies]
gleam_stdlib = ">= 0.52.0"
prng = ">= 4.0.2 and < 5.0.0"
exception = ">= 2.0.0 and < 3.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.1.2 and < 2.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
qcheck_gleeunit_utils = ">= 1.0.0 and < 2.0.0"
