name = "qcheck"
version = "0.0.2"

internal_modules = [
  "qcheck/utils",
  "qcheck/try",
  "qcheck/qtest/test_error",
  "qcheck/qtest/test_error_message",
]

description = "QuickCheck-inspired property testing with integrated shrinking"
licences = ["Apache-2.0", "MIT"]
repository = { type = "github", user = "mooreryan", repo = "gleam_qcheck" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
prng = "~> 3.0"
exception = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
birdie = ">= 1.1.2 and < 2.0.0"
gleeunit = "~> 1.0"
qcheck_gleeunit_utils = ">= 0.1.0 and < 0.2.0"
